spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.33.12:5432/admin
    username: admin-api
    password: password
flyway:
  user: admin-owner
  password: password
  url: jdbc:postgresql://192.168.33.12:5432/admin
  driver-class-name: org.postgresql.Driver
cross-origin-addresses: http://localhost:3000

---

spring:
  profiles: test

---

spring:
  profiles: ci
  datasource:
    url: jdbc:postgresql://192.168.1.10:5432/admin_test
flyway:
  url: jdbc:postgresql://192.168.1.10:5432/admin_test
server:
  port: 8081