---

- hosts: all
  become: yes

  vars_prompt:
      - name: "admin_owner_password"
        prompt: "Enter owner password"
        default: 'password'
        private: yes
      - name: "admin_api_password"
        prompt: "Enter admin api password"
        default: 'password'
        private: yes
  vars:
    local_file_name: "{{ lookup('pipe', 'ls -1 ../build/libs/*.jar') }}"

  tasks:
    - apt: name=software-properties-common
    - shell: 'add-apt-repository ppa:openjdk-r/ppa'
    - apt: name=openjdk-8-jdk
    - group: name=bootapp
    - user: name=bootapp group=bootapp shell=/usr/sbin/nologin
    - file: path=/var/adminapi/ state=directory owner=bootapp group=bootapp
    - copy: backup=yes src={{local_file_name}} dest=/var/adminapi/adminapi.jar mode=500 owner=bootapp group=bootapp
# bring back    - shell: 'chattr +i /var/adminapi/adminapi-0.0.1-SNAPSHOT.jar'
    - file: src=/var/adminapi/adminapi.jar dest=/etc/init.d/adminapi state=link
      when: ansible_distribution == 'Ubuntu'
    - copy: src=files/adminapi.service dest=/etc/systemd/system
      when: ansible_distribution == "Debian"
    - template: src=files/application.yml.j2 dest=/var/adminapi/application.yml
    - service: name=adminapi state=restarted