---

- hosts: db-servers
  become: yes

  vars_prompt:
    - name: "admin_owner_password"
      prompt: "Enter owner password"
      default: 'password'
      private: yes
    - name: "admin_api_password"
      prompt: "Enter admin api password"
      default: 'password'
      private: yes
  vars:
    postgresql_version: 9.4

    postgresql_databases:
      - name: "{{database_name}}"
        owner: admin-owner

    postgresql_users:
      - name: admin-owner
        pass: "{{admin_owner_password}}"

      - name: admin-api
        pass: "{{admin_api_password}}"

    postgresql_user_privileges:
      - name: admin-owner
        db: admin
        priv: "ALL"

    postgresql_user_privileges:
      - name: admin-api
        db: admin
        privs:
          - 'SELECT'
          - 'INSERT'
          - 'UPDATE'
          - 'DELETE'
          - 'USAGE'

    postgresql_listen_addresses:
      - "*"

    postgresql_pg_hba_default:
      - { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: '{{ postgresql_default_auth_method }}', comment: '' }
      - { type: local, database: all, user: all, address: '',             method: '{{ postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
      - { type: host,  database: all, user: all, address: '127.0.0.1/32', method: '{{ postgresql_default_auth_method }}', comment: 'IPv4 local connections:' }
      - { type: host,  database: all, user: all, address: '::1/128',      method: '{{ postgresql_default_auth_method }}', comment: 'IPv6 local connections:' }
      - { type: host,  database: all, user: all, address: '{{api_address}}', method: 'password'}

  roles:
      - role: ANXS.postgresql




