---

- hosts: db-servers
  become: yes

  vars:



    postgresql_version: 9.4

    postgresql_databases:
      - name: "{{database_name}}"
        owner: admin-owner

    postgresql_users:
      - name: admin-owner
        pass: "{{admin_owner_password}}"
        no_log: true

      - name: admin-api
        pass: "{{admin_api_password}}"
        no_log: true

    postgresql_user_privileges:
      - name: admin-owner
        db: "{{database_name}}"
        priv: "ALL"
      - name: admin-api
        db: "{{database_name}}"
        privs:
          - 'SELECT'
          - 'INSERT'
          - 'UPDATE'
          - 'DELETE'
          - 'USAGE'

    postgresql_listen_addresses:
      - "*"

    postgresql_pg_hba_default:
      - { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: '{{ postgresql_default_auth_method }}', comment: '' }
      - { type: local, database: all, user: all, address: '',             method: '{{ postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
      - { type: host,  database: all, user: all, address: '127.0.0.1/32', method: '{{ postgresql_default_auth_method }}', comment: 'IPv4 local connections:' }
      - { type: host,  database: all, user: all, address: '::1/128',      method: '{{ postgresql_default_auth_method }}', comment: 'IPv6 local connections:' }
      - { type: host,  database: all, user: all, address: '{{api_address}}', method: 'password'}

  pre_tasks:
    - set_fact:
        admin_api_password: "{{ lookup('password', '/var/lib/jenkins/secrets/admin_api.txt length=15') }}"
      when: admin_api_password is undefined
    - set_fact:
        admin_owner_password: "{{ lookup('password', '/var/lib/jenkins/secrets/admin_owner.txt length=15') }}"
      when: admin_owner_password is undefined

  roles:
      - role: ANXS.postgresql




